base_url = "https://sator-sdk.github.io"
title = "sator-sdk"
compile_sass = true
build_search_index = true
generate_feed = true
minify_html = true

theme = "apollo"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
use_cdn = false
theme = "toggle"

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
]

socials = [
    #{ name = "twitter", url = "", icon = "twitter" },
    { name = "github", url = "https://github.com/sator-sdk", icon = "github" },
    { name = "session", url = "", icon = "session" },
    { name = "briar", url = "", icon = "briar" },
    { name = "tox", url = "", icon = "tox" },
    { name = "keybase", url = "", icon = "keybase" },
]

[extra.analytics]
enabled = true
goatcounter_user = ""

