name: Build and Deploy
on:
  push:
    branches:
      - main

concurrency:
  group: "pages"
  cancel-in-progress: true
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Zola
        run: |
          curl -sSLf https://github.com/getzola/zola/releases/latest/download/install.sh | sh
      - name: Build Website
        run: zola build
      - name: Deploy to GitHub Pages
        uses: shalzz/zola-deploy-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
